global:
  security:
    allowInsecureImages: true
image:
  registry: ds-labs.cr.cloud.ru
  repository: keycloak
  tag: 26.0.7-debian-12-r0
postgresql:
  enabled: false
externalDatabase:
  host: postgres
  user: keycloak
  password: keycloakpass
  database: keycloakdb
  port: 5432
